/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description The API process is up. Does not touch PostgreSQL or Redis.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description PostgreSQL and Redis are both reachable.
         */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Batch */
        post: operations["create_batch_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batches/{batch_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description Register one file. An identical file is not saved unless confirm_duplicate is true.
         */
        post: operations["upload_file_batches__batch_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/ai-extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ai Extract Batch
         * @description Approve several files for an AI read. All or nothing.
         */
        post: operations["ai_extract_batch_files_ai_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_key}/ai-extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ai Extract
         * @description Approve one file for an AI read. The approval is recorded before anything is sent.
         */
        post: operations["ai_extract_files__file_key__ai_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ai Usage
         * @description For the sidebar: approved AI reads today against the daily cap, and the providers.
         */
        get: operations["ai_usage_ai_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Files */
        get: operations["get_files_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Counts per status, for the summary cards, chips and sidebar badges.
         */
        get: operations["get_summary_files_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/error-reports.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All Error Reports
         * @description The originals of every file needing attention, plus one combined PDF report.
         */
        get: operations["all_error_reports_files_error_reports_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get One File
         * @description One file, by id or reference number, with its receipts, flags and runs.
         */
        get: operations["get_one_file_files__file_key__get"];
        put?: never;
        post?: never;
        /**
         * Remove File
         * @description Delete a file with its runs, receipts and flags (D-019). Not while it is processing.
         */
        delete: operations["remove_file_files__file_key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_key}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download File
         * @description The original file, under its original name.
         */
        get: operations["download_file_files__file_key__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_key}/error-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Error Report
         * @description A PDF with the file's problems and what each reader found (D-031).
         */
        get: operations["error_report_files__file_key__error_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_key}/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save Receipts
         * @description Save a person's edits as the accepted result; the file becomes resolved (D-030).
         */
        put: operations["save_receipts_files__file_key__receipts_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_key}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject
         * @description Not a receipt, or a bad scan (D-030 item 4).
         */
        post: operations["reject_files__file_key__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description Built-in categories first, in their usual order, then custom ones A to Z.
         */
        get: operations["list_categories_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Category
         * @description Only custom categories that no receipt or vendor uses.
         */
        delete: operations["delete_category_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Rename Category */
        patch: operations["rename_category_categories__category_id__patch"];
        trace?: never;
    };
    "/flags/{flag_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve */
        post: operations["resolve_flags__flag_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AiBatchIn
         * @description Approval for several files at once (D-036).
         */
        AiBatchIn: {
            provider: components["schemas"]["AiProvider"];
            /**
             * Approved
             * @description Must be true: the person confirmed the file will be sent to the provider
             * @constant
             */
            approved: true;
            /**
             * Files
             * @description Ids or reference numbers
             */
            files: string[];
        };
        /**
         * AiExtractIn
         * @description Approval to send one file to an AI provider (hard rule 1).
         */
        AiExtractIn: {
            provider: components["schemas"]["AiProvider"];
            /**
             * Approved
             * @description Must be true: the person confirmed the file will be sent to the provider
             * @constant
             */
            approved: true;
        };
        /**
         * AiProvider
         * @enum {string}
         */
        AiProvider: "anthropic" | "openai";
        /** AiProviderInfo */
        AiProviderInfo: {
            provider: components["schemas"]["AiProvider"];
            /** Label */
            label: string;
            /** Model */
            model: string;
            /** Configured */
            configured: boolean;
        };
        /** AiRunOut */
        AiRunOut: {
            /** File Id */
            file_id: number;
            /** Ref No */
            ref_no: string;
            /** Run Id */
            run_id: number;
        };
        /** AiRunsOut */
        AiRunsOut: {
            /** Runs */
            runs: components["schemas"]["AiRunOut"][];
        };
        /** AiUsage */
        AiUsage: {
            /** Enabled */
            enabled: boolean;
            /** Daily Cap */
            daily_cap: number;
            /** Used Today */
            used_today: number;
            /** Remaining */
            remaining: number;
            /** Providers */
            providers: components["schemas"]["AiProviderInfo"][];
        };
        /** BatchDetail */
        BatchDetail: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Files */
            files: components["schemas"]["FileSummary"][];
        };
        /** BatchOut */
        BatchOut: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_upload_file_batches__batch_id__files_post */
        Body_upload_file_batches__batch_id__files_post: {
            /** File */
            file: string;
            /**
             * Confirm Duplicate
             * @default false
             */
            confirm_duplicate: boolean;
        };
        /**
         * CategoryIn
         * @description A category name: spacing tidied, 1 to 50 characters, no control characters.
         */
        CategoryIn: {
            /** Name */
            name: string;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Builtin */
            builtin: boolean;
            /**
             * In Use
             * @description Receipts and vendors using this category
             */
            in_use: number;
        };
        /**
         * DuplicateResult
         * @description Nothing was saved. Upload again with confirm_duplicate=true to keep a copy (D-015).
         */
        DuplicateResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            result: "duplicate";
            duplicate_of: components["schemas"]["FileRef"];
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string | null;
        };
        /**
         * FileCounts
         * @description For the summary cards, the status chips and the sidebar badges.
         */
        FileCounts: {
            /** Total */
            total: number;
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /**
             * With Warnings
             * @description Parsed files that have open warning flags
             */
            with_warnings: number;
            /**
             * Needs Attention
             * @description Needs review + flagged + parsed with warnings: the Review queue
             */
            needs_attention: number;
        };
        /**
         * FileDetail
         * @description Everything the Review page shows for one file.
         */
        FileDetail: {
            /** Id */
            id: number;
            /** Ref No */
            ref_no: string;
            /** Original Name */
            original_name: string;
            /** Size Bytes */
            size_bytes: number;
            kind: components["schemas"]["FileKind"] | null;
            status: components["schemas"]["FileStatus"];
            /** Error */
            error: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            duplicate_of: components["schemas"]["FileRef"] | null;
            /**
             * Open Flags
             * @description Unresolved problems a person should look at
             */
            open_flags: number;
            /** Receipts */
            receipts: components["schemas"]["ReceiptOut"][];
            /** Flags */
            flags: components["schemas"]["FlagOut"][];
            /** Runs */
            runs: components["schemas"]["RunOut"][];
        };
        /**
         * FileKind
         * @enum {string}
         */
        FileKind: "excel" | "csv" | "pdf_text" | "pdf_scan" | "image";
        /** FilePage */
        FilePage: {
            /** Items */
            items: components["schemas"]["FileSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * FileRef
         * @description Enough to name and link to a file.
         */
        FileRef: {
            /** Id */
            id: number;
            /** Ref No */
            ref_no: string;
            /** Original Name */
            original_name: string;
        };
        /**
         * FileStatus
         * @enum {string}
         */
        FileStatus: "pending" | "processing" | "parsed" | "needs_review" | "ai_processing" | "flagged" | "resolved" | "rejected" | "failed";
        /** FileSummary */
        FileSummary: {
            /** Id */
            id: number;
            /** Ref No */
            ref_no: string;
            /** Original Name */
            original_name: string;
            /** Size Bytes */
            size_bytes: number;
            kind: components["schemas"]["FileKind"] | null;
            status: components["schemas"]["FileStatus"];
            /** Error */
            error: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            duplicate_of: components["schemas"]["FileRef"] | null;
            /**
             * Open Flags
             * @description Unresolved problems a person should look at
             */
            open_flags: number;
        };
        /** FlagOut */
        FlagOut: {
            /** Id */
            id: number;
            type: components["schemas"]["FlagType"];
            severity: components["schemas"]["FlagSeverity"];
            /** Detail */
            detail: string;
            /** Receipt Id */
            receipt_id: number | null;
            /** Resolved */
            resolved: boolean;
            /** Resolved By */
            resolved_by: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FlagSeverity
         * @enum {string}
         */
        FlagSeverity: "info" | "warning" | "error";
        /**
         * FlagType
         * @enum {string}
         */
        FlagType: "unreadable" | "validation_failed" | "parser_conflict" | "duplicate_receipt" | "arithmetic_mismatch";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** LineItemIn */
        LineItemIn: {
            /** Description */
            description: string;
            /** Quantity */
            quantity?: number | string | null;
            /** Unit Price */
            unit_price?: number | string | null;
            /** Amount */
            amount: number | string;
        };
        /** LineItemOut */
        LineItemOut: {
            /** Position */
            position: number;
            /** Description */
            description: string;
            /** Quantity */
            quantity: string | null;
            /** Unit Price */
            unit_price: string | null;
            /** Amount */
            amount: string;
        };
        /** LineItemSchema */
        LineItemSchema: {
            /** Description */
            description: string;
            /** Quantity */
            quantity?: string | null;
            /** Unit Price */
            unit_price?: string | null;
            /** Amount */
            amount: string;
        };
        /** ManualEdit */
        ManualEdit: {
            /** Receipts */
            receipts: components["schemas"]["ReceiptIn"][];
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Database
             * @constant
             */
            database: "ok";
            /**
             * Redis
             * @constant
             */
            redis: "ok";
        };
        /**
         * ReceiptIn
         * @description A receipt as a person entered or corrected it on the Review page.
         */
        ReceiptIn: {
            /** Vendor */
            vendor: string;
            /** Receipt Number */
            receipt_number?: string | null;
            /**
             * Receipt Date
             * Format: date
             */
            receipt_date: string;
            /** Subtotal */
            subtotal?: number | string | null;
            /** Tax */
            tax?: number | string | null;
            /** Total */
            total: number | string;
            /**
             * Category Id
             * @description The person's category choice
             */
            category_id?: number | null;
            /** Line Items */
            line_items?: components["schemas"]["LineItemIn"][];
        };
        /** ReceiptOut */
        ReceiptOut: {
            /** Id */
            id: number;
            /** Ref No */
            ref_no: string;
            /** Seq */
            seq: number;
            /** Vendor */
            vendor: string;
            /** Receipt Number */
            receipt_number: string | null;
            /**
             * Receipt Date
             * Format: date
             */
            receipt_date: string;
            /** Subtotal */
            subtotal: string | null;
            /** Tax */
            tax: string | null;
            /** Total */
            total: string;
            /** Category Id */
            category_id: number | null;
            /** Category Auto Id */
            category_auto_id: number | null;
            /** Category Override Id */
            category_override_id: number | null;
            /** Confidence */
            confidence: number | null;
            /** Line Items */
            line_items: components["schemas"]["LineItemOut"][];
        };
        /** ReceiptSchema */
        ReceiptSchema: {
            /** Vendor */
            vendor?: string | null;
            /** Receipt Number */
            receipt_number?: string | null;
            /** Receipt Date */
            receipt_date?: string | null;
            /** Subtotal */
            subtotal?: string | null;
            /** Tax */
            tax?: string | null;
            /** Total */
            total?: string | null;
            /** Line Items */
            line_items?: components["schemas"]["LineItemSchema"][];
            /** Confidence */
            confidence: number;
            /** Source */
            source: string;
        };
        /** RegisteredResult */
        RegisteredResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            result: "registered";
            file: components["schemas"]["FileSummary"];
        };
        /** RejectIn */
        RejectIn: {
            /**
             * Reason
             * @description e.g. Not a receipt
             */
            reason: string;
        };
        /**
         * RunOut
         * @description One extraction attempt. `result` is what that reader found, accepted or not.
         */
        RunOut: {
            /** Id */
            id: number;
            parser: components["schemas"]["RunParser"];
            provider: components["schemas"]["AiProvider"] | null;
            /** Model */
            model: string | null;
            /** Confidence */
            confidence: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Accepted */
            accepted: boolean;
            /** Error */
            error: string | null;
            /** Ai Approved By */
            ai_approved_by: string | null;
            /** Ai Approved At */
            ai_approved_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Cached From Id */
            cached_from_id?: number | null;
            /** Result */
            result: components["schemas"]["ReceiptSchema"][] | null;
        };
        /**
         * RunParser
         * @enum {string}
         */
        RunParser: "excel" | "csv" | "pdf_text" | "pdf_scan" | "image" | "ai" | "manual";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_batch_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
        };
    };
    get_batch_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_batches__batch_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_batches__batch_id__files_post"];
            };
        };
        responses: {
            /** @description Identical file exists; nothing saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateResult"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredResult"] | components["schemas"]["DuplicateResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ai_extract_batch_files_ai_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiBatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiRunsOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ai_extract_files__file_key__ai_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiExtractIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiRunsOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ai_usage_ai_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiUsage"];
                };
            };
        };
    };
    get_files_files_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["FileStatus"] | null;
                /** @description Name or reference */
                q?: string | null;
                /** @description Only files a person should look at (the Review queue) */
                attention?: boolean;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_files_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileCounts"];
                };
            };
        };
    };
    all_error_reports_files_error_reports_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": unknown;
                };
            };
        };
    };
    get_one_file_files__file_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_file_files__file_key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_files__file_key__download_get: {
        parameters: {
            query?: {
                /** @description Show in the browser (PDFs and images) */
                inline?: boolean;
            };
            header?: never;
            path: {
                file_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    error_report_files__file_key__error_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_receipts_files__file_key__receipts_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reject_files__file_key__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_categories_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    create_category_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_category_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_flags__flag_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
